# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7693f19ac2d26201765ce1496b442961c33301d0d6fe9aa5b43ab2c77785d224099d4ab92c7ad4ebb6d028a67edb6f991a12bb04f26510f06a321aef9fcc631

test:
  secret_key_base: b9fc318ecdaaf178a18819d249a200c28f323ddb1866ffe6467b28085c146727800e56a84c935b10f7a8d183068d9f519f58c22521a62d8716e7bada5e92bb0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
